# Generated by Django 4.2.5 on 2023-10-09 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Profile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="address",
        ),
        migrations.CreateModel(
            name="Adress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=255, verbose_name="Фамилия")),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Имя компании"
                    ),
                ),
                (
                    "country",
                    models.PositiveIntegerField(
                        choices=[(1, "Russia"), (2, "USA")], verbose_name="Страна"
                    ),
                ),
                ("city", models.CharField(max_length=255, verbose_name="Город")),
                ("street", models.CharField(max_length=255, verbose_name="Улица")),
                (
                    "postcode",
                    models.CharField(max_length=255, verbose_name="Почтовый код"),
                ),
                (
                    "appartament",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Апартаменты"
                    ),
                ),
                ("email", models.CharField(max_length=255, verbose_name="email")),
                ("phone", models.CharField(max_length=255, verbose_name="Телефон")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
