# Generated by Django 4.2.5 on 2023-10-10 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Profile", "0004_alter_profile_default_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="default_address",
        ),
    ]
