# Generated by Django 4.2.5 on 2023-10-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Profile", "0009_adress_default"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="histories",
            name="product",
        ),
    ]
