# Generated by Django 4.2.5 on 2023-09-12 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallereis",
            name="variations",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gallereis",
                to="shops.variations",
                verbose_name="Вариация",
            ),
        ),
        migrations.AlterField(
            model_name="variations",
            name="products",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="variations",
                to="shops.products",
                verbose_name="Продукт",
            ),
        ),
    ]
