# Generated by Django 4.2.5 on 2023-09-17 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variationproducts",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="variationproduct",
                to="shops.products",
                verbose_name="Товар",
            ),
        ),
    ]
