# Generated by Django 4.2.5 on 2023-09-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0002_alter_gallereis_variations_alter_variations_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallereis",
            name="image",
            field=models.ImageField(upload_to="shops/", verbose_name="Картинка"),
        ),
    ]
