# Generated by Django 4.2.5 on 2023-09-18 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0002_alter_variationproducts_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attributs",
            name="variation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attributs",
                to="shops.variations",
                verbose_name="Вариации",
            ),
        ),
    ]
