# Generated by Django 4.2.5 on 2023-09-28 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shops", "0003_alter_attributs_variation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_products",
                    models.PositiveIntegerField(verbose_name="Количество продуктов"),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=9, verbose_name="Цена"
                    ),
                ),
                ("in_order", models.BooleanField()),
                ("for_anonymous", models.BooleanField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="cartproduct",
                        to="shops.products",
                        verbose_name="Продукты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Корзина",
                "verbose_name_plural": "Корзины",
            },
        ),
    ]
