# Generated by Django 4.2.5 on 2023-09-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0003_alter_gallereis_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="img",
            field=models.ImageField(
                upload_to="categories/", verbose_name="Изображение"
            ),
        ),
    ]
