# Generated by Django 4.2.5 on 2023-09-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0004_alter_categories_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="category",
            field=models.ManyToManyField(
                related_name="categories",
                to="shops.categories",
                verbose_name="Категория",
            ),
        ),
    ]
