# Generated by Django 4.2.5 on 2023-09-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0005_alter_products_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brands",
            name="logo",
            field=models.ImageField(upload_to="shops/brands/", verbose_name="Логотип"),
        ),
    ]
