# Generated by Django 4.2.5 on 2023-09-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0005_alter_carts_for_anonymous_alter_carts_in_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carts",
            name="total_products",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество продуктов"
            ),
        ),
    ]
