# Generated by Django 4.2.5 on 2023-10-02 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0006_alter_carts_total_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="variation",
        ),
        migrations.AddField(
            model_name="orders",
            name="appartament",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Апартаменты"
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="cart",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="shops.carts",
                verbose_name="Корзина",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orders",
            name="city",
            field=models.CharField(default=1, max_length=255, verbose_name="Город"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orders",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Имя компании"
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="country",
            field=models.PositiveIntegerField(
                choices=[(1, "Russia"), (2, "USA")], default=1, verbose_name="Страна"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orders",
            name="email",
            field=models.CharField(default=1, max_length=255, verbose_name="email"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orders",
            name="first_name",
            field=models.CharField(default=1, max_length=255, verbose_name="Имя"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orders",
            name="last_name",
            field=models.CharField(default=1, max_length=255, verbose_name="Фамилия"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orders",
            name="notes",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Примечания"
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="phone",
            field=models.CharField(default=1, max_length=255, verbose_name="Телефон"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orders",
            name="postcode",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Почтовый код"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orders",
            name="street",
            field=models.CharField(default=1, max_length=255, verbose_name="Улица"),
            preserve_default=False,
        ),
    ]
