# Generated by Django 4.2.5 on 2023-09-14 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0006_alter_brands_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviews",
                to="shops.products",
                verbose_name="Продукт",
            ),
        ),
    ]
