# Generated by Django 4.2.5 on 2023-09-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0007_alter_reviews_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="img",
            field=models.ImageField(
                upload_to="shops/categories/", verbose_name="Изображение"
            ),
        ),
    ]
