# Generated by Django 4.2.5 on 2023-10-07 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0008_alter_carts_final_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faqs",
            name="answer",
            field=models.TextField(blank=True, verbose_name="Ответ"),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="review",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Review must be at least 1"
                    ),
                    django.core.validators.MaxValueValidator(
                        5, message="Review cannot be more than 5"
                    ),
                ],
                verbose_name="Отзыв",
            ),
        ),
    ]
