# Generated by Django 4.2.5 on 2023-10-07 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0009_alter_faqs_answer_alter_reviews_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faqs",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="faqs",
                to="shops.products",
                verbose_name="Продукт",
            ),
        ),
    ]
