# Generated by Django 4.2.5 on 2023-10-12 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Profile", "0010_remove_histories_product"),
        ("shops", "0010_alter_faqs_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="appartament",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="city",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="country",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="email",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="postcode",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="street",
        ),
        migrations.AddField(
            model_name="orders",
            name="address",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="Profile.adress",
                verbose_name="Адрес",
            ),
        ),
    ]
