# Generated by Django 4.2.5 on 2023-10-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0013_wishlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlist",
            name="product",
        ),
        migrations.AddField(
            model_name="wishlist",
            name="product",
            field=models.ManyToManyField(
                blank=True, to="shops.products", verbose_name="Продукт"
            ),
        ),
    ]
