# Generated by Django 4.2.5 on 2023-10-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0014_remove_wishlist_product_wishlist_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributs",
            name="file",
            field=models.FileField(default=False, upload_to=""),
        ),
        migrations.AddField(
            model_name="attributs",
            name="files",
            field=models.BooleanField(default=False),
        ),
    ]
