# Generated by Django 4.2.5 on 2023-10-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0015_attributs_file_attributs_files"),
    ]

    operations = [
        migrations.CreateModel(
            name="SliderProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Описание"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="shops/sliders", verbose_name="Картинка"
                    ),
                ),
                (
                    "product",
                    models.ManyToManyField(to="shops.products", verbose_name="Продукт"),
                ),
            ],
            options={
                "verbose_name": "Товар для слайдера",
                "verbose_name_plural": "Товары для слайдера",
            },
        ),
        migrations.CreateModel(
            name="Sileders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ManyToManyField(
                        to="shops.sliderproduct", verbose_name="Продукт"
                    ),
                ),
            ],
            options={
                "verbose_name": "Слайдер",
                "verbose_name_plural": "Слайдеры",
            },
        ),
    ]
