# Generated by Django 4.2.5 on 2023-10-19 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0016_sliderproduct_sileders"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Sileders",
            new_name="Sliders",
        ),
    ]
