# Generated by Django 4.2.5 on 2023-10-19 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0017_rename_sileders_sliders"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sliderproduct",
            name="product",
        ),
        migrations.AddField(
            model_name="sliderproduct",
            name="product",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="shops.products",
                verbose_name="Продукт",
            ),
        ),
    ]
