# Generated by Django 4.2.5 on 2023-10-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0018_remove_sliderproduct_product_sliderproduct_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bannders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ManyToManyField(
                        to="shops.sliderproduct", verbose_name="Продукт"
                    ),
                ),
            ],
            options={
                "verbose_name": "Баннер",
                "verbose_name_plural": "Баннеры",
            },
        ),
    ]
