# Generated by Django 4.2.5 on 2023-10-19 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0019_bannders"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bannders",
            new_name="Banners",
        ),
    ]
