# Generated by Django 4.2.5 on 2023-10-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0020_rename_bannders_banners"),
    ]

    operations = [
        migrations.AddField(
            model_name="banners",
            name="description",
            field=models.CharField(
                default=False, max_length=255, verbose_name="Описание"
            ),
        ),
        migrations.AddField(
            model_name="banners",
            name="image",
            field=models.ImageField(
                default=False, upload_to="shops/banners", verbose_name="Картинка"
            ),
        ),
    ]
