# Generated by Django 4.2.5 on 2023-10-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0021_banners_description_banners_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banners",
            name="product",
            field=models.ManyToManyField(to="shops.products", verbose_name="Продукт"),
        ),
    ]
