# Generated by Django 4.2.5 on 2023-10-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0022_alter_banners_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="products",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="products",
            name="name_en",
            field=models.CharField(max_length=250, null=True, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="products",
            name="name_ru",
            field=models.CharField(max_length=250, null=True, verbose_name="Имя"),
        ),
    ]
