# Generated by Django 4.2.5 on 2023-10-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0023_products_description_en_products_description_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributs",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="attributs",
            name="name_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="brands",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="brands",
            name="name_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="categories",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="categories",
            name="name_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="tags",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="tags",
            name="name_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="variations",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="variations",
            name="name_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Имя"),
        ),
    ]
