# Generated by Django 4.2.5 on 2023-10-19 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shops", "0024_attributs_name_en_attributs_name_ru_brands_name_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "description",
                    models.CharField(
                        default=False, max_length=255, verbose_name="Описание"
                    ),
                ),
                ("contacts", models.CharField(max_length=255, verbose_name="Контакты")),
                (
                    "product",
                    models.ManyToManyField(to="shops.products", verbose_name="Продукт"),
                ),
            ],
            options={
                "verbose_name": "Магазин",
                "verbose_name_plural": "Магазины",
            },
        ),
        migrations.CreateModel(
            name="StoresReviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.CharField(max_length=255, verbose_name="Отзыв")),
                ("date", models.DateField(auto_now=True, verbose_name="Дата")),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shops.stores",
                        verbose_name="Магазин",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв о магазине",
                "verbose_name_plural": "Отзывы о магазине",
            },
        ),
    ]
