# Generated by Django 4.2.5 on 2023-10-20 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0025_stores_storesreviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="storesreviews",
            name="text",
            field=models.CharField(default=False, max_length=255, verbose_name="Отзыв"),
        ),
        migrations.AlterField(
            model_name="storesreviews",
            name="review",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Review must be at least 1"
                    ),
                    django.core.validators.MaxValueValidator(
                        5, message="Review cannot be more than 5"
                    ),
                ],
                verbose_name="Отзыв",
            ),
        ),
    ]
