# Generated by Django 4.2.5 on 2023-10-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0026_storesreviews_text_alter_storesreviews_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="stores",
            name="slug",
            field=models.SlugField(
                default=False, max_length=200, unique=True, verbose_name="URL"
            ),
        ),
    ]
