# Generated by Django 4.2.5 on 2023-10-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0030_alter_storesreviews_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storesreviews",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="storesreviews",
                to="shops.stores",
                verbose_name="Магазин",
            ),
        ),
        migrations.AlterField(
            model_name="storesreviews",
            name="text",
            field=models.CharField(max_length=255, verbose_name="Текст"),
        ),
    ]
