# Generated by Django 4.2.5 on 2023-10-25 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shops", "0031_alter_storesreviews_store_alter_storesreviews_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Claims",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        default=False, max_length=255, verbose_name="Описание"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="shops/claims", verbose_name="Картинка"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shops.cartproduct",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Претензия",
                "verbose_name_plural": "Претензии",
            },
        ),
        migrations.RemoveField(
            model_name="storesreviews",
            name="store",
        ),
        migrations.RemoveField(
            model_name="storesreviews",
            name="user",
        ),
        migrations.DeleteModel(
            name="Sliders",
        ),
        migrations.DeleteModel(
            name="StoresReviews",
        ),
    ]
