# Generated by Django 4.2.5 on 2023-10-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0035_alter_claims_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="claims",
            name="date",
            field=models.DateField(auto_now=True, verbose_name="Дата"),
        ),
    ]
